// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93uE4-TYN1L5KgC-YR_I4NWj8zEnPLjE',
    appId: '1:394506446005:web:2f7c5b4e4282cf1460cafc',
    messagingSenderId: '394506446005',
    projectId: 'orbix-flutter-app',
    authDomain: 'orbix-flutter-app.firebaseapp.com',
    storageBucket: 'orbix-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXMxZ5bmfwMXi8G0RlUCsjRWWJrjXSco',
    appId: '1:394506446005:android:642ad39e0a36b6fb60cafc',
    messagingSenderId: '394506446005',
    projectId: 'orbix-flutter-app',
    storageBucket: 'orbix-flutter-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumVeHWFtPSibCXoqRK9GGpL5nt0zgIH0',
    appId: '1:394506446005:ios:594d83e3ab5cefd660cafc',
    messagingSenderId: '394506446005',
    projectId: 'orbix-flutter-app',
    storageBucket: 'orbix-flutter-app.firebasestorage.app',
    iosBundleId: 'com.orbix.orbixFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumVeHWFtPSibCXoqRK9GGpL5nt0zgIH0',
    appId: '1:394506446005:ios:594d83e3ab5cefd660cafc',
    messagingSenderId: '394506446005',
    projectId: 'orbix-flutter-app',
    storageBucket: 'orbix-flutter-app.firebasestorage.app',
    iosBundleId: 'com.orbix.orbixFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB93uE4-TYN1L5KgC-YR_I4NWj8zEnPLjE',
    appId: '1:394506446005:web:1d875209971ce87f60cafc',
    messagingSenderId: '394506446005',
    projectId: 'orbix-flutter-app',
    authDomain: 'orbix-flutter-app.firebaseapp.com',
    storageBucket: 'orbix-flutter-app.firebasestorage.app',
  );
}
